### ISSUE TITLE
A lot of mp3s don't have a title

### ISSUE THREAD

**Issue by Wikunia** [BenOckmore/mutagen#29] opened 2014-07-22 16:27 UTC
It's me again. Hope I am not stupid...
I am using: 

```
tags = mutagen.File(path, easy=True)
print(tags.pprint())
```

(path is absolute)
And some mp3s have a title attr but only a few. I can read the title attribute inside the Windows (v8.1) explorer.

**Comment by BenOckmore** [comment] 2014-07-22 16:41
Hey again,

There are a few possibilities here:
1. The tags might not be stored in the standard ID3 format. Windows may be showing other tags, such as APEv2.
2. The tags might be stored as ID3v1 and not being picked up with ID3v2 tags.
3. Something's broken.

To test this a little more thoroughly, could you run the following code, and upload the output on pastebin:

```
import mutagen.id3
tags = mutagen.id3.ID3(path_with_title)
print(tags.version)
print(tags.pprint())
tags = mutagen.id3.ID3(path_with_no_title)
print(tags.version)
print(tags.pprint())
f = open(path_with_no_title, "rb")
print(repr(f.read(512)))
```

It might also be a good idea to install Python 2.7, and test whether the titles show up using mutagenx on there. If not, it would also be good to know whether the problem happens when you use the original mutagen package (at https://bitbucket.org/lazka/mutagen).

Thanks for helping debug!

**Comment by Wikunia** [comment] 2014-07-22 16:45
Error:
`No module named mutagen.ID3`

**Comment by BenOckmore** [comment] 2014-07-22 16:46
Oh, sorry, that should be lowercase (mutagen.id3). I've edited the original too (the class name is mutagen.id3.ID3).

**Comment by Wikunia** [comment] 2014-07-22 16:50
I got this error message:
`'module' object is not callable`
in line `tags=mutagen.id3(path)`

**Comment by BenOckmore** [comment] 2014-07-22 16:51
Yes - see the updated comment. I made a couple of mistakes in the code snippet which should be fixed now!

**Comment by Wikunia** [comment] 2014-07-22 16:55
The output file: http://pastebin.com/aGxJd64c

**Comment by Wikunia** [comment] 2014-07-22 17:14
Same output using Python2.7 I will test the original version...

**Comment by BenOckmore** [comment] 2014-07-22 17:16
It looks as though the problem is that the second file is using ID3v2.2 tag names (Eg. TT2 intead of TIT2), while stating in the header that it is ID3v2.3 (see the first byte after ID3 - \x03).

I don't really have a solution to this - looking at the ID3 code, there seems to be no way to manually set the version between reading the ID3 header and loading the frames. Looking at the code from the original mutagen project, this seems to be a problem there too. I've opened a ticket at https://bitbucket.org/lazka/mutagen .

If I get some time I'll look into this, but hopefully you'll be able to still use the package for most of your files without much trouble. If you really need a workaround, it might work if you replace the 4th byte of the file with a 2 instead of a 3 (although then you'd lose access to the id3v2.3 tags).

**Comment by Wikunia** [comment] 2014-07-22 17:24
Well I don't need it immediately only want to code a little :D 
So don't hurry and close the issue if you fixed it ;)

**Comment by lazka** [comment] 2014-07-22 17:35
Can you send me and/or @LordSputnik the file per mail?

**Comment by Wikunia** [comment] 2014-07-22 18:11
Can you give me your mail adress? :)

**Comment by lazka** [comment] 2014-09-20 16:14
Fixed by https://bitbucket.org/lazka/mutagen/commits/f3be08763f42

**Closed as completed** 2014-09-20 21:54 UTC
